### ISSUE TITLE
Add an URL-Checker

### ISSUE THREAD

**Issue by rwachtler** [rwachtler/ITM13TermStatistics#19]
## Requirement
During the process of adding a new domain, a domain check should be performed which verifies that the user input is a valid URL. 

**NOTE:** Should return a notification to the user, that the given URL is invalid. *(optional)*

**Comment by bambuschop** [comment]
On the one hand it would be nice to check if the user entered something like "fbsdcvr" as URL and return a notification to the user that this is not a valid URL.

On the other hand we should trigger a small AJAX call to see if e.g. "http://a.xx" is valid. Sending a call to the page and waiting for the status code would be sufficient. Status 200 = ok, everything else means the site is not valid.
