### ISSUE TITLE
Parallel Crawlers aren't working as expected

### ISSUE THREAD

**Issue by LordSimal** [rwachtler/ITM13TermStatistics#21]
If more than one crawler (= more than one website is crawled at the same time) is working at the same time, the analyzing process can't start until every crawler-thread (even the ones that don't belong to the same website) is finished.

**Comment by bambuschop** [comment]
Does anyone know a work around or is there a setting for the crawler config to change the behaviour?

**Comment by bambuschop** [comment]
https://code.google.com/p/crawler4j/source/browse/src/test/java/edu/uci/ics/crawler4j/examples/multiple/MultipleCrawlerController.java?r=d362515f7d300dcdb1fe7ca2b08c92c5c363f9c4

@medman506 found this example code
